//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosConsumidorFinal
    {
        public int confi_Id { get; set; }
        public long fact_Id { get; set; }
        public string confi_Nombres { get; set; }
        public string confi_Telefono { get; set; }
        public string confi_Correo { get; set; }
    
        public virtual tbFactura tbFactura { get; set; }
    }
}
