//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_ZORZAL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERP_ZORZALEntities : DbContext
    {
        public ERP_ZORZALEntities()
            : base("name=ERP_ZORZALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbAccesoRol> tbAccesoRol { get; set; }
        public virtual DbSet<tbRoles> tbRoles { get; set; }
        public virtual DbSet<tbRolesUsuario> tbRolesUsuario { get; set; }
        public virtual DbSet<tbUsuario> tbUsuario { get; set; }
        public virtual DbSet<tbActividadEconomica> tbActividadEconomica { get; set; }
        public virtual DbSet<tbBanco> tbBanco { get; set; }
        public virtual DbSet<tbCuentasBanco> tbCuentasBanco { get; set; }
        public virtual DbSet<tbDepartamento> tbDepartamento { get; set; }
        public virtual DbSet<tbDocumentoFiscal> tbDocumentoFiscal { get; set; }
        public virtual DbSet<tbEstadoInventarioFisico> tbEstadoInventarioFisico { get; set; }
        public virtual DbSet<tbMoneda> tbMoneda { get; set; }
        public virtual DbSet<tbMunicipio> tbMunicipio { get; set; }
        public virtual DbSet<tbTipoIdentificacion> tbTipoIdentificacion { get; set; }
        public virtual DbSet<tbTiposEntrada> tbTiposEntrada { get; set; }
        public virtual DbSet<tbTiposSalida> tbTiposSalida { get; set; }
        public virtual DbSet<tbUnidadesMedida> tbUnidadesMedida { get; set; }
        public virtual DbSet<tbBodega> tbBodega { get; set; }
        public virtual DbSet<tbBodegaDetalle> tbBodegaDetalle { get; set; }
        public virtual DbSet<tbCaja> tbCaja { get; set; }
        public virtual DbSet<tbEntrada> tbEntrada { get; set; }
        public virtual DbSet<tbEstadoMovimiento> tbEstadoMovimiento { get; set; }
        public virtual DbSet<tbInventarioFisicoDetalle> tbInventarioFisicoDetalle { get; set; }
        public virtual DbSet<tbProducto> tbProducto { get; set; }
        public virtual DbSet<tbProductoCategoria> tbProductoCategoria { get; set; }
        public virtual DbSet<tbProductoSubcategoria> tbProductoSubcategoria { get; set; }
        public virtual DbSet<tbProveedor> tbProveedor { get; set; }
        public virtual DbSet<tbSalida> tbSalida { get; set; }
        public virtual DbSet<tbSalidaDetalle> tbSalidaDetalle { get; set; }
        public virtual DbSet<tbArqueoCaja> tbArqueoCaja { get; set; }
        public virtual DbSet<tbCaja1> tbCaja1 { get; set; }
        public virtual DbSet<tbCliente> tbCliente { get; set; }
        public virtual DbSet<tbCuponDescuento> tbCuponDescuento { get; set; }
        public virtual DbSet<tbDetalleFactura> tbDetalleFactura { get; set; }
        public virtual DbSet<tbDevolucion> tbDevolucion { get; set; }
        public virtual DbSet<tbDevolucionDetalle> tbDevolucionDetalle { get; set; }
        public virtual DbSet<tbEstadoFactura> tbEstadoFactura { get; set; }
        public virtual DbSet<tbEstadoSolicitudCredito> tbEstadoSolicitudCredito { get; set; }
        public virtual DbSet<tbExoneracion> tbExoneracion { get; set; }
        public virtual DbSet<tbFactura> tbFactura { get; set; }
        public virtual DbSet<tbListadoPrecioDetalle> tbListadoPrecioDetalle { get; set; }
        public virtual DbSet<tbListaPrecio> tbListaPrecio { get; set; }
        public virtual DbSet<tbNotaCredito> tbNotaCredito { get; set; }
        public virtual DbSet<tbPago> tbPago { get; set; }
        public virtual DbSet<tbPedido> tbPedido { get; set; }
        public virtual DbSet<tbPedidoDetalle> tbPedidoDetalle { get; set; }
        public virtual DbSet<tbPuntoEmision> tbPuntoEmision { get; set; }
        public virtual DbSet<tbPuntoEmisionDetalle> tbPuntoEmisionDetalle { get; set; }
        public virtual DbSet<tbSolicitudCredito> tbSolicitudCredito { get; set; }
        public virtual DbSet<tbSolicitudEfectivo> tbSolicitudEfectivo { get; set; }
        public virtual DbSet<tbSucursal> tbSucursal { get; set; }
        public virtual DbSet<tbTipoPago> tbTipoPago { get; set; }
        public virtual DbSet<tbObjeto> tbObjeto { get; set; }
        public virtual DbSet<tbEntradaDetalle> tbEntradaDetalle { get; set; }
        public virtual DbSet<tbInventarioFisico> tbInventarioFisico { get; set; }
    }
}
