//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_ZORZAL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ERP_ZORZALEntities : DbContext
    {
        public ERP_ZORZALEntities()
            : base("name=ERP_ZORZALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbInventarioFisico> tbInventarioFisico { get; set; }
        public virtual DbSet<tbAccesoRol> tbAccesoRol { get; set; }
        public virtual DbSet<tbObjeto> tbObjeto { get; set; }
        public virtual DbSet<tbRol> tbRol { get; set; }
        public virtual DbSet<tbRolesUsuario> tbRolesUsuario { get; set; }
        public virtual DbSet<tbUsuario> tbUsuario { get; set; }
        public virtual DbSet<tbActividadEconomica> tbActividadEconomica { get; set; }
        public virtual DbSet<tbBanco> tbBanco { get; set; }
        public virtual DbSet<tbCuentasBanco> tbCuentasBanco { get; set; }
        public virtual DbSet<tbDenominacion> tbDenominacion { get; set; }
        public virtual DbSet<tbDepartamento> tbDepartamento { get; set; }
        public virtual DbSet<tbMoneda> tbMoneda { get; set; }
        public virtual DbSet<tbMunicipio> tbMunicipio { get; set; }
        public virtual DbSet<tbTipoIdentificacion> tbTipoIdentificacion { get; set; }
        public virtual DbSet<tbUnidadMedida> tbUnidadMedida { get; set; }
        public virtual DbSet<tbBodega> tbBodega { get; set; }
        public virtual DbSet<tbBodegaDetalle> tbBodegaDetalle { get; set; }
        public virtual DbSet<tbBox> tbBox { get; set; }
        public virtual DbSet<tbEntrada> tbEntrada { get; set; }
        public virtual DbSet<tbEntradaDetalle> tbEntradaDetalle { get; set; }
        public virtual DbSet<tbEstadoInventarioFisico> tbEstadoInventarioFisico { get; set; }
        public virtual DbSet<tbEstadoMovimiento> tbEstadoMovimiento { get; set; }
        public virtual DbSet<tbInventarioFisicoDetalle> tbInventarioFisicoDetalle { get; set; }
        public virtual DbSet<tbProducto> tbProducto { get; set; }
        public virtual DbSet<tbProductoCategoria> tbProductoCategoria { get; set; }
        public virtual DbSet<tbProductoSubcategoria> tbProductoSubcategoria { get; set; }
        public virtual DbSet<tbProveedor> tbProveedor { get; set; }
        public virtual DbSet<tbSalida> tbSalida { get; set; }
        public virtual DbSet<tbSalidaDetalle> tbSalidaDetalle { get; set; }
        public virtual DbSet<tbTipoEntrada> tbTipoEntrada { get; set; }
        public virtual DbSet<tbTipoSalida> tbTipoSalida { get; set; }
        public virtual DbSet<tbArqueoCaja> tbArqueoCaja { get; set; }
        public virtual DbSet<tbCaja> tbCaja { get; set; }
        public virtual DbSet<tbCliente> tbCliente { get; set; }
        public virtual DbSet<tbCuponDescuento> tbCuponDescuento { get; set; }
        public virtual DbSet<tbDevolucion> tbDevolucion { get; set; }
        public virtual DbSet<tbDevolucionDetalle> tbDevolucionDetalle { get; set; }
        public virtual DbSet<tbDocumentoFiscal> tbDocumentoFiscal { get; set; }
        public virtual DbSet<tbEstadoFactura> tbEstadoFactura { get; set; }
        public virtual DbSet<tbEstadoSolicitudCredito> tbEstadoSolicitudCredito { get; set; }
        public virtual DbSet<tbExoneracion> tbExoneracion { get; set; }
        public virtual DbSet<tbFactura> tbFactura { get; set; }
        public virtual DbSet<tbFacturaDetalle> tbFacturaDetalle { get; set; }
        public virtual DbSet<tbFacturaHistorica> tbFacturaHistorica { get; set; }
        public virtual DbSet<tbListadoPrecioDetalle> tbListadoPrecioDetalle { get; set; }
        public virtual DbSet<tbListaPrecio> tbListaPrecio { get; set; }
        public virtual DbSet<tbNotaCredito> tbNotaCredito { get; set; }
        public virtual DbSet<tbPago> tbPago { get; set; }
        public virtual DbSet<tbPedido> tbPedido { get; set; }
        public virtual DbSet<tbPedidoDetalle> tbPedidoDetalle { get; set; }
        public virtual DbSet<tbPuntoEmision> tbPuntoEmision { get; set; }
        public virtual DbSet<tbPuntoEmisionDetalle> tbPuntoEmisionDetalle { get; set; }
        public virtual DbSet<tbSolicitudCredito> tbSolicitudCredito { get; set; }
        public virtual DbSet<tbSolicitudEfectivo> tbSolicitudEfectivo { get; set; }
        public virtual DbSet<tbSolicitudEfectivoDetalle> tbSolicitudEfectivoDetalle { get; set; }
        public virtual DbSet<tbSucursal> tbSucursal { get; set; }
        public virtual DbSet<tbTipoPago> tbTipoPago { get; set; }
    
        public virtual ObjectResult<string> spGetMunicipios(string codDepartamento)
        {
            var codDepartamentoParameter = codDepartamento != null ?
                new ObjectParameter("CodDepartamento", codDepartamento) :
                new ObjectParameter("CodDepartamento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spGetMunicipios", codDepartamentoParameter);
        }
    
        public virtual ObjectResult<UDP_Gral_tbBanco_Insert_Result> UDP_Gral_tbBanco_Insert(string ban_Nombre, string ban_NombreContacto, string ban_TelefonoContacto)
        {
            var ban_NombreParameter = ban_Nombre != null ?
                new ObjectParameter("ban_Nombre", ban_Nombre) :
                new ObjectParameter("ban_Nombre", typeof(string));
    
            var ban_NombreContactoParameter = ban_NombreContacto != null ?
                new ObjectParameter("ban_NombreContacto", ban_NombreContacto) :
                new ObjectParameter("ban_NombreContacto", typeof(string));
    
            var ban_TelefonoContactoParameter = ban_TelefonoContacto != null ?
                new ObjectParameter("ban_TelefonoContacto", ban_TelefonoContacto) :
                new ObjectParameter("ban_TelefonoContacto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_Gral_tbBanco_Insert_Result>("UDP_Gral_tbBanco_Insert", ban_NombreParameter, ban_NombreContactoParameter, ban_TelefonoContactoParameter);
        }
    
        public virtual ObjectResult<UDP_Gral_tbBanco_Update_Result> UDP_Gral_tbBanco_Update(Nullable<short> ban_Id, string ban_Nombre, string ban_NombreContacto, string ban_TelefonoContacto, Nullable<int> ban_UsuarioCrea, Nullable<System.DateTime> ban_FechaCrea, Nullable<int> ban_UsuarioModifica, Nullable<System.DateTime> ban_FechaModifica)
        {
            var ban_IdParameter = ban_Id.HasValue ?
                new ObjectParameter("ban_Id", ban_Id) :
                new ObjectParameter("ban_Id", typeof(short));
    
            var ban_NombreParameter = ban_Nombre != null ?
                new ObjectParameter("ban_Nombre", ban_Nombre) :
                new ObjectParameter("ban_Nombre", typeof(string));
    
            var ban_NombreContactoParameter = ban_NombreContacto != null ?
                new ObjectParameter("ban_NombreContacto", ban_NombreContacto) :
                new ObjectParameter("ban_NombreContacto", typeof(string));
    
            var ban_TelefonoContactoParameter = ban_TelefonoContacto != null ?
                new ObjectParameter("ban_TelefonoContacto", ban_TelefonoContacto) :
                new ObjectParameter("ban_TelefonoContacto", typeof(string));
    
            var ban_UsuarioCreaParameter = ban_UsuarioCrea.HasValue ?
                new ObjectParameter("ban_UsuarioCrea", ban_UsuarioCrea) :
                new ObjectParameter("ban_UsuarioCrea", typeof(int));
    
            var ban_FechaCreaParameter = ban_FechaCrea.HasValue ?
                new ObjectParameter("ban_FechaCrea", ban_FechaCrea) :
                new ObjectParameter("ban_FechaCrea", typeof(System.DateTime));
    
            var ban_UsuarioModificaParameter = ban_UsuarioModifica.HasValue ?
                new ObjectParameter("ban_UsuarioModifica", ban_UsuarioModifica) :
                new ObjectParameter("ban_UsuarioModifica", typeof(int));
    
            var ban_FechaModificaParameter = ban_FechaModifica.HasValue ?
                new ObjectParameter("ban_FechaModifica", ban_FechaModifica) :
                new ObjectParameter("ban_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_Gral_tbBanco_Update_Result>("UDP_Gral_tbBanco_Update", ban_IdParameter, ban_NombreParameter, ban_NombreContactoParameter, ban_TelefonoContactoParameter, ban_UsuarioCreaParameter, ban_FechaCreaParameter, ban_UsuarioModificaParameter, ban_FechaModificaParameter);
        }
    }
}
