//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ERP_ZORZALEntities : DbContext
    {
        public ERP_ZORZALEntities()
            : base("name=ERP_ZORZALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbInventarioFisico> tbInventarioFisico { get; set; }
        public virtual DbSet<tbAccesoRol> tbAccesoRol { get; set; }
        public virtual DbSet<tbObjeto> tbObjeto { get; set; }
        public virtual DbSet<tbRol> tbRol { get; set; }
        public virtual DbSet<tbRolesUsuario> tbRolesUsuario { get; set; }
        public virtual DbSet<tbUsuario> tbUsuario { get; set; }
        public virtual DbSet<tbActividadEconomica> tbActividadEconomica { get; set; }
        public virtual DbSet<tbBanco> tbBanco { get; set; }
        public virtual DbSet<tbCuentasBanco> tbCuentasBanco { get; set; }
        public virtual DbSet<tbDenominacion> tbDenominacion { get; set; }
        public virtual DbSet<tbDepartamento> tbDepartamento { get; set; }
        public virtual DbSet<tbEmpleado> tbEmpleado { get; set; }
        public virtual DbSet<tbMoneda> tbMoneda { get; set; }
        public virtual DbSet<tbMunicipio> tbMunicipio { get; set; }
        public virtual DbSet<tbParametro> tbParametro { get; set; }
        public virtual DbSet<tbTipoIdentificacion> tbTipoIdentificacion { get; set; }
        public virtual DbSet<tbUnidadMedida> tbUnidadMedida { get; set; }
        public virtual DbSet<tbBodega> tbBodega { get; set; }
        public virtual DbSet<tbBodegaDetalle> tbBodegaDetalle { get; set; }
        public virtual DbSet<tbBox> tbBox { get; set; }
        public virtual DbSet<tbEntrada> tbEntrada { get; set; }
        public virtual DbSet<tbEntradaDetalle> tbEntradaDetalle { get; set; }
        public virtual DbSet<tbEstadoInventarioFisico> tbEstadoInventarioFisico { get; set; }
        public virtual DbSet<tbEstadoMovimiento> tbEstadoMovimiento { get; set; }
        public virtual DbSet<tbInventarioFisicoDetalle> tbInventarioFisicoDetalle { get; set; }
        public virtual DbSet<tbProducto> tbProducto { get; set; }
        public virtual DbSet<tbProductoCategoria> tbProductoCategoria { get; set; }
        public virtual DbSet<tbProductoSubcategoria> tbProductoSubcategoria { get; set; }
        public virtual DbSet<tbProveedor> tbProveedor { get; set; }
        public virtual DbSet<tbSalida> tbSalida { get; set; }
        public virtual DbSet<tbSalidaDetalle> tbSalidaDetalle { get; set; }
        public virtual DbSet<tbTipoEntrada> tbTipoEntrada { get; set; }
        public virtual DbSet<tbTipoSalida> tbTipoSalida { get; set; }
        public virtual DbSet<tbCaja> tbCaja { get; set; }
        public virtual DbSet<tbCliente> tbCliente { get; set; }
        public virtual DbSet<tbCuponDescuento> tbCuponDescuento { get; set; }
        public virtual DbSet<tbDenominacionArqueo> tbDenominacionArqueo { get; set; }
        public virtual DbSet<tbDevolucion> tbDevolucion { get; set; }
        public virtual DbSet<tbDevolucionDetalle> tbDevolucionDetalle { get; set; }
        public virtual DbSet<tbDocumentoFiscal> tbDocumentoFiscal { get; set; }
        public virtual DbSet<tbEstadoFactura> tbEstadoFactura { get; set; }
        public virtual DbSet<tbEstadoPedido> tbEstadoPedido { get; set; }
        public virtual DbSet<tbEstadoSolicitudCredito> tbEstadoSolicitudCredito { get; set; }
        public virtual DbSet<tbExoneracion> tbExoneracion { get; set; }
        public virtual DbSet<tbFactura> tbFactura { get; set; }
        public virtual DbSet<tbFacturaDetalle> tbFacturaDetalle { get; set; }
        public virtual DbSet<tbFacturaHistorica> tbFacturaHistorica { get; set; }
        public virtual DbSet<tbListadoPrecioDetalle> tbListadoPrecioDetalle { get; set; }
        public virtual DbSet<tbListaPrecio> tbListaPrecio { get; set; }
        public virtual DbSet<tbMovimientoCaja> tbMovimientoCaja { get; set; }
        public virtual DbSet<tbNotaCredito> tbNotaCredito { get; set; }
        public virtual DbSet<tbPago> tbPago { get; set; }
        public virtual DbSet<tbPedido> tbPedido { get; set; }
        public virtual DbSet<tbPedidoDetalle> tbPedidoDetalle { get; set; }
        public virtual DbSet<tbPuntoEmision> tbPuntoEmision { get; set; }
        public virtual DbSet<tbPuntoEmisionDetalle> tbPuntoEmisionDetalle { get; set; }
        public virtual DbSet<tbSolicitudCredito> tbSolicitudCredito { get; set; }
        public virtual DbSet<tbSolicitudEfectivo> tbSolicitudEfectivo { get; set; }
        public virtual DbSet<tbSolicitudEfectivoDetalle> tbSolicitudEfectivoDetalle { get; set; }
        public virtual DbSet<tbSucursal> tbSucursal { get; set; }
        public virtual DbSet<tbTipoPago> tbTipoPago { get; set; }
    
        public virtual ObjectResult<UDP_Gral_tbBanco_Insert_Result> UDP_Gral_tbBanco_Insert(string ban_Nombre, string ban_NombreContacto, string ban_TelefonoContacto)
        {
            var ban_NombreParameter = ban_Nombre != null ?
                new ObjectParameter("ban_Nombre", ban_Nombre) :
                new ObjectParameter("ban_Nombre", typeof(string));
    
            var ban_NombreContactoParameter = ban_NombreContacto != null ?
                new ObjectParameter("ban_NombreContacto", ban_NombreContacto) :
                new ObjectParameter("ban_NombreContacto", typeof(string));
    
            var ban_TelefonoContactoParameter = ban_TelefonoContacto != null ?
                new ObjectParameter("ban_TelefonoContacto", ban_TelefonoContacto) :
                new ObjectParameter("ban_TelefonoContacto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_Gral_tbBanco_Insert_Result>("UDP_Gral_tbBanco_Insert", ban_NombreParameter, ban_NombreContactoParameter, ban_TelefonoContactoParameter);
        }
    
        public virtual ObjectResult<UDP_Gral_tbBanco_Update_Result> UDP_Gral_tbBanco_Update(Nullable<short> ban_Id, string ban_Nombre, string ban_NombreContacto, string ban_TelefonoContacto, Nullable<int> ban_UsuarioCrea, Nullable<System.DateTime> ban_FechaCrea)
        {
            var ban_IdParameter = ban_Id.HasValue ?
                new ObjectParameter("ban_Id", ban_Id) :
                new ObjectParameter("ban_Id", typeof(short));
    
            var ban_NombreParameter = ban_Nombre != null ?
                new ObjectParameter("ban_Nombre", ban_Nombre) :
                new ObjectParameter("ban_Nombre", typeof(string));
    
            var ban_NombreContactoParameter = ban_NombreContacto != null ?
                new ObjectParameter("ban_NombreContacto", ban_NombreContacto) :
                new ObjectParameter("ban_NombreContacto", typeof(string));
    
            var ban_TelefonoContactoParameter = ban_TelefonoContacto != null ?
                new ObjectParameter("ban_TelefonoContacto", ban_TelefonoContacto) :
                new ObjectParameter("ban_TelefonoContacto", typeof(string));
    
            var ban_UsuarioCreaParameter = ban_UsuarioCrea.HasValue ?
                new ObjectParameter("ban_UsuarioCrea", ban_UsuarioCrea) :
                new ObjectParameter("ban_UsuarioCrea", typeof(int));
    
            var ban_FechaCreaParameter = ban_FechaCrea.HasValue ?
                new ObjectParameter("ban_FechaCrea", ban_FechaCrea) :
                new ObjectParameter("ban_FechaCrea", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_Gral_tbBanco_Update_Result>("UDP_Gral_tbBanco_Update", ban_IdParameter, ban_NombreParameter, ban_NombreContactoParameter, ban_TelefonoContactoParameter, ban_UsuarioCreaParameter, ban_FechaCreaParameter);
        }
    
        public virtual ObjectResult<UDP_Gral_tbDenominacion_Insert_Result> UDP_Gral_tbDenominacion_Insert(string deno_Descripcion, Nullable<byte> deno_Tipo, Nullable<decimal> deno_valor, Nullable<short> mnda_Id)
        {
            var deno_DescripcionParameter = deno_Descripcion != null ?
                new ObjectParameter("deno_Descripcion", deno_Descripcion) :
                new ObjectParameter("deno_Descripcion", typeof(string));
    
            var deno_TipoParameter = deno_Tipo.HasValue ?
                new ObjectParameter("deno_Tipo", deno_Tipo) :
                new ObjectParameter("deno_Tipo", typeof(byte));
    
            var deno_valorParameter = deno_valor.HasValue ?
                new ObjectParameter("deno_valor", deno_valor) :
                new ObjectParameter("deno_valor", typeof(decimal));
    
            var mnda_IdParameter = mnda_Id.HasValue ?
                new ObjectParameter("mnda_Id", mnda_Id) :
                new ObjectParameter("mnda_Id", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_Gral_tbDenominacion_Insert_Result>("UDP_Gral_tbDenominacion_Insert", deno_DescripcionParameter, deno_TipoParameter, deno_valorParameter, mnda_IdParameter);
        }
    
        public virtual ObjectResult<UDP_Gral_tbTipoIdentificacion_Insert_Result> UDP_Gral_tbTipoIdentificacion_Insert(string tpi_Descripcion)
        {
            var tpi_DescripcionParameter = tpi_Descripcion != null ?
                new ObjectParameter("tpi_Descripcion", tpi_Descripcion) :
                new ObjectParameter("tpi_Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_Gral_tbTipoIdentificacion_Insert_Result>("UDP_Gral_tbTipoIdentificacion_Insert", tpi_DescripcionParameter);
        }
    
        public virtual ObjectResult<UDP_Vent_tbCaja_Insert_Result> UDP_Vent_tbCaja_Insert(Nullable<short> cja_Id, string cja_Descripcion, Nullable<short> suc_Id)
        {
            var cja_IdParameter = cja_Id.HasValue ?
                new ObjectParameter("cja_Id", cja_Id) :
                new ObjectParameter("cja_Id", typeof(short));
    
            var cja_DescripcionParameter = cja_Descripcion != null ?
                new ObjectParameter("cja_Descripcion", cja_Descripcion) :
                new ObjectParameter("cja_Descripcion", typeof(string));
    
            var suc_IdParameter = suc_Id.HasValue ?
                new ObjectParameter("suc_Id", suc_Id) :
                new ObjectParameter("suc_Id", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_Vent_tbCaja_Insert_Result>("UDP_Vent_tbCaja_Insert", cja_IdParameter, cja_DescripcionParameter, suc_IdParameter);
        }
    
        public virtual ObjectResult<UDP_Vent_tbCaja_Update_Result> UDP_Vent_tbCaja_Update(Nullable<short> cja_Id, string cja_Descripcion, Nullable<short> suc_Id, Nullable<int> cja_UsuarioCrea, Nullable<System.DateTime> cja_FechaCrea, Nullable<int> cja_UsuarioModifica, Nullable<System.DateTime> cja_FechaModifica)
        {
            var cja_IdParameter = cja_Id.HasValue ?
                new ObjectParameter("cja_Id", cja_Id) :
                new ObjectParameter("cja_Id", typeof(short));
    
            var cja_DescripcionParameter = cja_Descripcion != null ?
                new ObjectParameter("cja_Descripcion", cja_Descripcion) :
                new ObjectParameter("cja_Descripcion", typeof(string));
    
            var suc_IdParameter = suc_Id.HasValue ?
                new ObjectParameter("suc_Id", suc_Id) :
                new ObjectParameter("suc_Id", typeof(short));
    
            var cja_UsuarioCreaParameter = cja_UsuarioCrea.HasValue ?
                new ObjectParameter("cja_UsuarioCrea", cja_UsuarioCrea) :
                new ObjectParameter("cja_UsuarioCrea", typeof(int));
    
            var cja_FechaCreaParameter = cja_FechaCrea.HasValue ?
                new ObjectParameter("cja_FechaCrea", cja_FechaCrea) :
                new ObjectParameter("cja_FechaCrea", typeof(System.DateTime));
    
            var cja_UsuarioModificaParameter = cja_UsuarioModifica.HasValue ?
                new ObjectParameter("cja_UsuarioModifica", cja_UsuarioModifica) :
                new ObjectParameter("cja_UsuarioModifica", typeof(int));
    
            var cja_FechaModificaParameter = cja_FechaModifica.HasValue ?
                new ObjectParameter("cja_FechaModifica", cja_FechaModifica) :
                new ObjectParameter("cja_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_Vent_tbCaja_Update_Result>("UDP_Vent_tbCaja_Update", cja_IdParameter, cja_DescripcionParameter, suc_IdParameter, cja_UsuarioCreaParameter, cja_FechaCreaParameter, cja_UsuarioModificaParameter, cja_FechaModificaParameter);
        }
    
        public virtual ObjectResult<UDP_Gral_tbCuentasBanco_Insert_Result> UDP_Gral_tbCuentasBanco_Insert(Nullable<short> ban_Id, Nullable<short> mnda_Id, Nullable<byte> bcta_TipoCuenta, Nullable<decimal> bcta_TotalCredito, Nullable<decimal> bcta_TotalDebito, Nullable<System.DateTime> bcta_FechaApertura, string bcta_Numero)
        {
            var ban_IdParameter = ban_Id.HasValue ?
                new ObjectParameter("ban_Id", ban_Id) :
                new ObjectParameter("ban_Id", typeof(short));
    
            var mnda_IdParameter = mnda_Id.HasValue ?
                new ObjectParameter("mnda_Id", mnda_Id) :
                new ObjectParameter("mnda_Id", typeof(short));
    
            var bcta_TipoCuentaParameter = bcta_TipoCuenta.HasValue ?
                new ObjectParameter("bcta_TipoCuenta", bcta_TipoCuenta) :
                new ObjectParameter("bcta_TipoCuenta", typeof(byte));
    
            var bcta_TotalCreditoParameter = bcta_TotalCredito.HasValue ?
                new ObjectParameter("bcta_TotalCredito", bcta_TotalCredito) :
                new ObjectParameter("bcta_TotalCredito", typeof(decimal));
    
            var bcta_TotalDebitoParameter = bcta_TotalDebito.HasValue ?
                new ObjectParameter("bcta_TotalDebito", bcta_TotalDebito) :
                new ObjectParameter("bcta_TotalDebito", typeof(decimal));
    
            var bcta_FechaAperturaParameter = bcta_FechaApertura.HasValue ?
                new ObjectParameter("bcta_FechaApertura", bcta_FechaApertura) :
                new ObjectParameter("bcta_FechaApertura", typeof(System.DateTime));
    
            var bcta_NumeroParameter = bcta_Numero != null ?
                new ObjectParameter("bcta_Numero", bcta_Numero) :
                new ObjectParameter("bcta_Numero", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_Gral_tbCuentasBanco_Insert_Result>("UDP_Gral_tbCuentasBanco_Insert", ban_IdParameter, mnda_IdParameter, bcta_TipoCuentaParameter, bcta_TotalCreditoParameter, bcta_TotalDebitoParameter, bcta_FechaAperturaParameter, bcta_NumeroParameter);
        }
    
        public virtual ObjectResult<UDP_Gral_tbCuentasBanco_Update_Result> UDP_Gral_tbCuentasBanco_Update(Nullable<short> bcta_Id, Nullable<short> ban_Id, Nullable<short> mnda_Id, Nullable<byte> bcta_TipoCuenta, Nullable<decimal> bcta_TotalCredito, Nullable<decimal> bcta_TotalDebito, Nullable<System.DateTime> bcta_FechaApertura, string bcta_Numero, Nullable<int> bcta_UsuarioCrea, Nullable<System.DateTime> bcta_FechaCrea)
        {
            var bcta_IdParameter = bcta_Id.HasValue ?
                new ObjectParameter("bcta_Id", bcta_Id) :
                new ObjectParameter("bcta_Id", typeof(short));
    
            var ban_IdParameter = ban_Id.HasValue ?
                new ObjectParameter("ban_Id", ban_Id) :
                new ObjectParameter("ban_Id", typeof(short));
    
            var mnda_IdParameter = mnda_Id.HasValue ?
                new ObjectParameter("mnda_Id", mnda_Id) :
                new ObjectParameter("mnda_Id", typeof(short));
    
            var bcta_TipoCuentaParameter = bcta_TipoCuenta.HasValue ?
                new ObjectParameter("bcta_TipoCuenta", bcta_TipoCuenta) :
                new ObjectParameter("bcta_TipoCuenta", typeof(byte));
    
            var bcta_TotalCreditoParameter = bcta_TotalCredito.HasValue ?
                new ObjectParameter("bcta_TotalCredito", bcta_TotalCredito) :
                new ObjectParameter("bcta_TotalCredito", typeof(decimal));
    
            var bcta_TotalDebitoParameter = bcta_TotalDebito.HasValue ?
                new ObjectParameter("bcta_TotalDebito", bcta_TotalDebito) :
                new ObjectParameter("bcta_TotalDebito", typeof(decimal));
    
            var bcta_FechaAperturaParameter = bcta_FechaApertura.HasValue ?
                new ObjectParameter("bcta_FechaApertura", bcta_FechaApertura) :
                new ObjectParameter("bcta_FechaApertura", typeof(System.DateTime));
    
            var bcta_NumeroParameter = bcta_Numero != null ?
                new ObjectParameter("bcta_Numero", bcta_Numero) :
                new ObjectParameter("bcta_Numero", typeof(string));
    
            var bcta_UsuarioCreaParameter = bcta_UsuarioCrea.HasValue ?
                new ObjectParameter("bcta_UsuarioCrea", bcta_UsuarioCrea) :
                new ObjectParameter("bcta_UsuarioCrea", typeof(int));
    
            var bcta_FechaCreaParameter = bcta_FechaCrea.HasValue ?
                new ObjectParameter("bcta_FechaCrea", bcta_FechaCrea) :
                new ObjectParameter("bcta_FechaCrea", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_Gral_tbCuentasBanco_Update_Result>("UDP_Gral_tbCuentasBanco_Update", bcta_IdParameter, ban_IdParameter, mnda_IdParameter, bcta_TipoCuentaParameter, bcta_TotalCreditoParameter, bcta_TotalDebitoParameter, bcta_FechaAperturaParameter, bcta_NumeroParameter, bcta_UsuarioCreaParameter, bcta_FechaCreaParameter);
        }
    
        public virtual ObjectResult<UDP_Gral_tbActividadEconomica_Insert_Result> UDP_Gral_tbActividadEconomica_Insert(string acte_Descripcion)
        {
            var acte_DescripcionParameter = acte_Descripcion != null ?
                new ObjectParameter("acte_Descripcion", acte_Descripcion) :
                new ObjectParameter("acte_Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_Gral_tbActividadEconomica_Insert_Result>("UDP_Gral_tbActividadEconomica_Insert", acte_DescripcionParameter);
        }
    
        public virtual ObjectResult<UDP_Gral_tbActividadEconomica_Update_Result> UDP_Gral_tbActividadEconomica_Update(Nullable<short> acte_Id, string acte_Descripcion, Nullable<int> acte_UsuarioCrea, Nullable<System.DateTime> acte_FechaCrea, Nullable<int> acte_UsuarioModifica, Nullable<System.DateTime> acte_FechaModifica)
        {
            var acte_IdParameter = acte_Id.HasValue ?
                new ObjectParameter("acte_Id", acte_Id) :
                new ObjectParameter("acte_Id", typeof(short));
    
            var acte_DescripcionParameter = acte_Descripcion != null ?
                new ObjectParameter("acte_Descripcion", acte_Descripcion) :
                new ObjectParameter("acte_Descripcion", typeof(string));
    
            var acte_UsuarioCreaParameter = acte_UsuarioCrea.HasValue ?
                new ObjectParameter("acte_UsuarioCrea", acte_UsuarioCrea) :
                new ObjectParameter("acte_UsuarioCrea", typeof(int));
    
            var acte_FechaCreaParameter = acte_FechaCrea.HasValue ?
                new ObjectParameter("acte_FechaCrea", acte_FechaCrea) :
                new ObjectParameter("acte_FechaCrea", typeof(System.DateTime));
    
            var acte_UsuarioModificaParameter = acte_UsuarioModifica.HasValue ?
                new ObjectParameter("acte_UsuarioModifica", acte_UsuarioModifica) :
                new ObjectParameter("acte_UsuarioModifica", typeof(int));
    
            var acte_FechaModificaParameter = acte_FechaModifica.HasValue ?
                new ObjectParameter("acte_FechaModifica", acte_FechaModifica) :
                new ObjectParameter("acte_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_Gral_tbActividadEconomica_Update_Result>("UDP_Gral_tbActividadEconomica_Update", acte_IdParameter, acte_DescripcionParameter, acte_UsuarioCreaParameter, acte_FechaCreaParameter, acte_UsuarioModificaParameter, acte_FechaModificaParameter);
        }
    
        public virtual ObjectResult<UDP_Gral_tbMoneda_Insert_Result> UDP_Gral_tbMoneda_Insert(string mnda_Abreviatura, string mnda_Nombre)
        {
            var mnda_AbreviaturaParameter = mnda_Abreviatura != null ?
                new ObjectParameter("mnda_Abreviatura", mnda_Abreviatura) :
                new ObjectParameter("mnda_Abreviatura", typeof(string));
    
            var mnda_NombreParameter = mnda_Nombre != null ?
                new ObjectParameter("mnda_Nombre", mnda_Nombre) :
                new ObjectParameter("mnda_Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_Gral_tbMoneda_Insert_Result>("UDP_Gral_tbMoneda_Insert", mnda_AbreviaturaParameter, mnda_NombreParameter);
        }
    
        public virtual ObjectResult<UDP_Gral_tbMoneda_Update_Result> UDP_Gral_tbMoneda_Update(Nullable<short> mnda_Id, string mnda_Abreviatura, string mnda_Nombre, Nullable<int> mnda_UsuarioCrea, Nullable<System.DateTime> mnda_FechaCrea, Nullable<int> mnda_UsuarioModifica, Nullable<System.DateTime> mnda_FechaModifica)
        {
            var mnda_IdParameter = mnda_Id.HasValue ?
                new ObjectParameter("mnda_Id", mnda_Id) :
                new ObjectParameter("mnda_Id", typeof(short));
    
            var mnda_AbreviaturaParameter = mnda_Abreviatura != null ?
                new ObjectParameter("mnda_Abreviatura", mnda_Abreviatura) :
                new ObjectParameter("mnda_Abreviatura", typeof(string));
    
            var mnda_NombreParameter = mnda_Nombre != null ?
                new ObjectParameter("mnda_Nombre", mnda_Nombre) :
                new ObjectParameter("mnda_Nombre", typeof(string));
    
            var mnda_UsuarioCreaParameter = mnda_UsuarioCrea.HasValue ?
                new ObjectParameter("mnda_UsuarioCrea", mnda_UsuarioCrea) :
                new ObjectParameter("mnda_UsuarioCrea", typeof(int));
    
            var mnda_FechaCreaParameter = mnda_FechaCrea.HasValue ?
                new ObjectParameter("mnda_FechaCrea", mnda_FechaCrea) :
                new ObjectParameter("mnda_FechaCrea", typeof(System.DateTime));
    
            var mnda_UsuarioModificaParameter = mnda_UsuarioModifica.HasValue ?
                new ObjectParameter("mnda_UsuarioModifica", mnda_UsuarioModifica) :
                new ObjectParameter("mnda_UsuarioModifica", typeof(int));
    
            var mnda_FechaModificaParameter = mnda_FechaModifica.HasValue ?
                new ObjectParameter("mnda_FechaModifica", mnda_FechaModifica) :
                new ObjectParameter("mnda_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_Gral_tbMoneda_Update_Result>("UDP_Gral_tbMoneda_Update", mnda_IdParameter, mnda_AbreviaturaParameter, mnda_NombreParameter, mnda_UsuarioCreaParameter, mnda_FechaCreaParameter, mnda_UsuarioModificaParameter, mnda_FechaModificaParameter);
        }
    
        public virtual ObjectResult<UDP_Vent_tbTipoPago_Insert_Result> UDP_Vent_tbTipoPago_Insert(string tpa_Descripcion, Nullable<bool> tpa_Emisor, Nullable<bool> tpa_Cuenta, Nullable<bool> tpa_FechaVencimiento, Nullable<bool> tpa_Titular)
        {
            var tpa_DescripcionParameter = tpa_Descripcion != null ?
                new ObjectParameter("tpa_Descripcion", tpa_Descripcion) :
                new ObjectParameter("tpa_Descripcion", typeof(string));
    
            var tpa_EmisorParameter = tpa_Emisor.HasValue ?
                new ObjectParameter("tpa_Emisor", tpa_Emisor) :
                new ObjectParameter("tpa_Emisor", typeof(bool));
    
            var tpa_CuentaParameter = tpa_Cuenta.HasValue ?
                new ObjectParameter("tpa_Cuenta", tpa_Cuenta) :
                new ObjectParameter("tpa_Cuenta", typeof(bool));
    
            var tpa_FechaVencimientoParameter = tpa_FechaVencimiento.HasValue ?
                new ObjectParameter("tpa_FechaVencimiento", tpa_FechaVencimiento) :
                new ObjectParameter("tpa_FechaVencimiento", typeof(bool));
    
            var tpa_TitularParameter = tpa_Titular.HasValue ?
                new ObjectParameter("tpa_Titular", tpa_Titular) :
                new ObjectParameter("tpa_Titular", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_Vent_tbTipoPago_Insert_Result>("UDP_Vent_tbTipoPago_Insert", tpa_DescripcionParameter, tpa_EmisorParameter, tpa_CuentaParameter, tpa_FechaVencimientoParameter, tpa_TitularParameter);
        }
    
        public virtual ObjectResult<UDP_Vent_tbTipoPago_Update_Result> UDP_Vent_tbTipoPago_Update(Nullable<short> tpa_Id, string tpa_Descripcion, Nullable<bool> tpa_Emisor, Nullable<bool> tpa_Cuenta, Nullable<bool> tpa_FechaVencimiento, Nullable<bool> tpa_Titular, Nullable<int> tpa_UsuarioCrea, Nullable<System.DateTime> tpa_FechaCrea, Nullable<int> tpa_UsuarioModifica, Nullable<System.DateTime> tpa_FechaModifica)
        {
            var tpa_IdParameter = tpa_Id.HasValue ?
                new ObjectParameter("tpa_Id", tpa_Id) :
                new ObjectParameter("tpa_Id", typeof(short));
    
            var tpa_DescripcionParameter = tpa_Descripcion != null ?
                new ObjectParameter("tpa_Descripcion", tpa_Descripcion) :
                new ObjectParameter("tpa_Descripcion", typeof(string));
    
            var tpa_EmisorParameter = tpa_Emisor.HasValue ?
                new ObjectParameter("tpa_Emisor", tpa_Emisor) :
                new ObjectParameter("tpa_Emisor", typeof(bool));
    
            var tpa_CuentaParameter = tpa_Cuenta.HasValue ?
                new ObjectParameter("tpa_Cuenta", tpa_Cuenta) :
                new ObjectParameter("tpa_Cuenta", typeof(bool));
    
            var tpa_FechaVencimientoParameter = tpa_FechaVencimiento.HasValue ?
                new ObjectParameter("tpa_FechaVencimiento", tpa_FechaVencimiento) :
                new ObjectParameter("tpa_FechaVencimiento", typeof(bool));
    
            var tpa_TitularParameter = tpa_Titular.HasValue ?
                new ObjectParameter("tpa_Titular", tpa_Titular) :
                new ObjectParameter("tpa_Titular", typeof(bool));
    
            var tpa_UsuarioCreaParameter = tpa_UsuarioCrea.HasValue ?
                new ObjectParameter("tpa_UsuarioCrea", tpa_UsuarioCrea) :
                new ObjectParameter("tpa_UsuarioCrea", typeof(int));
    
            var tpa_FechaCreaParameter = tpa_FechaCrea.HasValue ?
                new ObjectParameter("tpa_FechaCrea", tpa_FechaCrea) :
                new ObjectParameter("tpa_FechaCrea", typeof(System.DateTime));
    
            var tpa_UsuarioModificaParameter = tpa_UsuarioModifica.HasValue ?
                new ObjectParameter("tpa_UsuarioModifica", tpa_UsuarioModifica) :
                new ObjectParameter("tpa_UsuarioModifica", typeof(int));
    
            var tpa_FechaModificaParameter = tpa_FechaModifica.HasValue ?
                new ObjectParameter("tpa_FechaModifica", tpa_FechaModifica) :
                new ObjectParameter("tpa_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_Vent_tbTipoPago_Update_Result>("UDP_Vent_tbTipoPago_Update", tpa_IdParameter, tpa_DescripcionParameter, tpa_EmisorParameter, tpa_CuentaParameter, tpa_FechaVencimientoParameter, tpa_TitularParameter, tpa_UsuarioCreaParameter, tpa_FechaCreaParameter, tpa_UsuarioModificaParameter, tpa_FechaModificaParameter);
        }
    
        public virtual ObjectResult<Nullable<short>> UDP_Vent_tbFactura_Select(Nullable<long> fact_Id)
        {
            var fact_IdParameter = fact_Id.HasValue ?
                new ObjectParameter("fact_Id", fact_Id) :
                new ObjectParameter("fact_Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<short>>("UDP_Vent_tbFactura_Select", fact_IdParameter);
        }
    
        public virtual ObjectResult<Nullable<short>> UDP_Vent_tbPedido_Select(Nullable<int> ped_Id)
        {
            var ped_IdParameter = ped_Id.HasValue ?
                new ObjectParameter("ped_Id", ped_Id) :
                new ObjectParameter("ped_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<short>>("UDP_Vent_tbPedido_Select", ped_IdParameter);
        }
    
        public virtual ObjectResult<string> spGetMunicipios(string codDepartamento)
        {
            var codDepartamentoParameter = codDepartamento != null ?
                new ObjectParameter("CodDepartamento", codDepartamento) :
                new ObjectParameter("CodDepartamento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spGetMunicipios", codDepartamentoParameter);
        }
    
        public virtual ObjectResult<UDP_Gral_tbTipoIdentificacion_Update_Result> UDP_Gral_tbTipoIdentificacion_Update(Nullable<byte> tpi_Id, string tpi_Descripcion, Nullable<int> tpi_UsuarioCrea, Nullable<System.DateTime> tpi_FechaCrea, Nullable<int> tpi_UsuarioModifica, Nullable<System.DateTime> tpi_FechaModifica)
        {
            var tpi_IdParameter = tpi_Id.HasValue ?
                new ObjectParameter("tpi_Id", tpi_Id) :
                new ObjectParameter("tpi_Id", typeof(byte));
    
            var tpi_DescripcionParameter = tpi_Descripcion != null ?
                new ObjectParameter("tpi_Descripcion", tpi_Descripcion) :
                new ObjectParameter("tpi_Descripcion", typeof(string));
    
            var tpi_UsuarioCreaParameter = tpi_UsuarioCrea.HasValue ?
                new ObjectParameter("tpi_UsuarioCrea", tpi_UsuarioCrea) :
                new ObjectParameter("tpi_UsuarioCrea", typeof(int));
    
            var tpi_FechaCreaParameter = tpi_FechaCrea.HasValue ?
                new ObjectParameter("tpi_FechaCrea", tpi_FechaCrea) :
                new ObjectParameter("tpi_FechaCrea", typeof(System.DateTime));
    
            var tpi_UsuarioModificaParameter = tpi_UsuarioModifica.HasValue ?
                new ObjectParameter("tpi_UsuarioModifica", tpi_UsuarioModifica) :
                new ObjectParameter("tpi_UsuarioModifica", typeof(int));
    
            var tpi_FechaModificaParameter = tpi_FechaModifica.HasValue ?
                new ObjectParameter("tpi_FechaModifica", tpi_FechaModifica) :
                new ObjectParameter("tpi_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_Gral_tbTipoIdentificacion_Update_Result>("UDP_Gral_tbTipoIdentificacion_Update", tpi_IdParameter, tpi_DescripcionParameter, tpi_UsuarioCreaParameter, tpi_FechaCreaParameter, tpi_UsuarioModificaParameter, tpi_FechaModificaParameter);
        }
    
        public virtual ObjectResult<UDP_Vent_tbEstadoSolicitudCredito_Insert_Result> UDP_Vent_tbEstadoSolicitudCredito_Insert(string escre_Descripcion)
        {
            var escre_DescripcionParameter = escre_Descripcion != null ?
                new ObjectParameter("escre_Descripcion", escre_Descripcion) :
                new ObjectParameter("escre_Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_Vent_tbEstadoSolicitudCredito_Insert_Result>("UDP_Vent_tbEstadoSolicitudCredito_Insert", escre_DescripcionParameter);
        }
    
        public virtual ObjectResult<UDP_Gral_tbDenominacion_Update_Result> UDP_Gral_tbDenominacion_Update(Nullable<short> deno_Id, string deno_Descripcion, Nullable<byte> deno_Tipo, Nullable<decimal> deno_valor, Nullable<short> mnda_Id, Nullable<int> deno_UsuarioCrea, Nullable<System.DateTime> deno_FechaCrea)
        {
            var deno_IdParameter = deno_Id.HasValue ?
                new ObjectParameter("deno_Id", deno_Id) :
                new ObjectParameter("deno_Id", typeof(short));
    
            var deno_DescripcionParameter = deno_Descripcion != null ?
                new ObjectParameter("deno_Descripcion", deno_Descripcion) :
                new ObjectParameter("deno_Descripcion", typeof(string));
    
            var deno_TipoParameter = deno_Tipo.HasValue ?
                new ObjectParameter("deno_Tipo", deno_Tipo) :
                new ObjectParameter("deno_Tipo", typeof(byte));
    
            var deno_valorParameter = deno_valor.HasValue ?
                new ObjectParameter("deno_valor", deno_valor) :
                new ObjectParameter("deno_valor", typeof(decimal));
    
            var mnda_IdParameter = mnda_Id.HasValue ?
                new ObjectParameter("mnda_Id", mnda_Id) :
                new ObjectParameter("mnda_Id", typeof(short));
    
            var deno_UsuarioCreaParameter = deno_UsuarioCrea.HasValue ?
                new ObjectParameter("deno_UsuarioCrea", deno_UsuarioCrea) :
                new ObjectParameter("deno_UsuarioCrea", typeof(int));
    
            var deno_FechaCreaParameter = deno_FechaCrea.HasValue ?
                new ObjectParameter("deno_FechaCrea", deno_FechaCrea) :
                new ObjectParameter("deno_FechaCrea", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_Gral_tbDenominacion_Update_Result>("UDP_Gral_tbDenominacion_Update", deno_IdParameter, deno_DescripcionParameter, deno_TipoParameter, deno_valorParameter, mnda_IdParameter, deno_UsuarioCreaParameter, deno_FechaCreaParameter);
        }
    
        public virtual ObjectResult<UDP_Vent_tbPuntoEmision_Insert_Result> UDP_Vent_tbPuntoEmision_Insert(string pemi_NumeroCAI)
        {
            var pemi_NumeroCAIParameter = pemi_NumeroCAI != null ?
                new ObjectParameter("pemi_NumeroCAI", pemi_NumeroCAI) :
                new ObjectParameter("pemi_NumeroCAI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_Vent_tbPuntoEmision_Insert_Result>("UDP_Vent_tbPuntoEmision_Insert", pemi_NumeroCAIParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> UDP_Vent_tbPuntoEmision_Update(Nullable<int> pemi_Id, string pemi_NumeroCAI, Nullable<int> pemi_UsuarioCrea, Nullable<System.DateTime> pemi_FechaCrea)
        {
            var pemi_IdParameter = pemi_Id.HasValue ?
                new ObjectParameter("pemi_Id", pemi_Id) :
                new ObjectParameter("pemi_Id", typeof(int));
    
            var pemi_NumeroCAIParameter = pemi_NumeroCAI != null ?
                new ObjectParameter("pemi_NumeroCAI", pemi_NumeroCAI) :
                new ObjectParameter("pemi_NumeroCAI", typeof(string));
    
            var pemi_UsuarioCreaParameter = pemi_UsuarioCrea.HasValue ?
                new ObjectParameter("pemi_UsuarioCrea", pemi_UsuarioCrea) :
                new ObjectParameter("pemi_UsuarioCrea", typeof(int));
    
            var pemi_FechaCreaParameter = pemi_FechaCrea.HasValue ?
                new ObjectParameter("pemi_FechaCrea", pemi_FechaCrea) :
                new ObjectParameter("pemi_FechaCrea", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UDP_Vent_tbPuntoEmision_Update", pemi_IdParameter, pemi_NumeroCAIParameter, pemi_UsuarioCreaParameter, pemi_FechaCreaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> UDP_Vent_tbPuntoEmisionDetalle_Update(Nullable<int> pemid_Id, string pemid_RangoInicio, string pemid_RangoFinal, Nullable<System.DateTime> pemid_FechaLimite, Nullable<int> pemid_UsuarioCrea, Nullable<System.DateTime> pemid_FechaCrea)
        {
            var pemid_IdParameter = pemid_Id.HasValue ?
                new ObjectParameter("pemid_Id", pemid_Id) :
                new ObjectParameter("pemid_Id", typeof(int));
    
            var pemid_RangoInicioParameter = pemid_RangoInicio != null ?
                new ObjectParameter("pemid_RangoInicio", pemid_RangoInicio) :
                new ObjectParameter("pemid_RangoInicio", typeof(string));
    
            var pemid_RangoFinalParameter = pemid_RangoFinal != null ?
                new ObjectParameter("pemid_RangoFinal", pemid_RangoFinal) :
                new ObjectParameter("pemid_RangoFinal", typeof(string));
    
            var pemid_FechaLimiteParameter = pemid_FechaLimite.HasValue ?
                new ObjectParameter("pemid_FechaLimite", pemid_FechaLimite) :
                new ObjectParameter("pemid_FechaLimite", typeof(System.DateTime));
    
            var pemid_UsuarioCreaParameter = pemid_UsuarioCrea.HasValue ?
                new ObjectParameter("pemid_UsuarioCrea", pemid_UsuarioCrea) :
                new ObjectParameter("pemid_UsuarioCrea", typeof(int));
    
            var pemid_FechaCreaParameter = pemid_FechaCrea.HasValue ?
                new ObjectParameter("pemid_FechaCrea", pemid_FechaCrea) :
                new ObjectParameter("pemid_FechaCrea", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UDP_Vent_tbPuntoEmisionDetalle_Update", pemid_IdParameter, pemid_RangoInicioParameter, pemid_RangoFinalParameter, pemid_FechaLimiteParameter, pemid_UsuarioCreaParameter, pemid_FechaCreaParameter);
        }
    
        public virtual ObjectResult<UDP_Vent_tbPuntoEmisionDetalle_Insert_Result> UDP_Vent_tbPuntoEmisionDetalle_Insert(Nullable<int> pemi_Id, string dfisc_Id, string pemid_RangoInicio, string pemid_RangoFinal, Nullable<System.DateTime> pemid_FechaLimite)
        {
            var pemi_IdParameter = pemi_Id.HasValue ?
                new ObjectParameter("pemi_Id", pemi_Id) :
                new ObjectParameter("pemi_Id", typeof(int));
    
            var dfisc_IdParameter = dfisc_Id != null ?
                new ObjectParameter("dfisc_Id", dfisc_Id) :
                new ObjectParameter("dfisc_Id", typeof(string));
    
            var pemid_RangoInicioParameter = pemid_RangoInicio != null ?
                new ObjectParameter("pemid_RangoInicio", pemid_RangoInicio) :
                new ObjectParameter("pemid_RangoInicio", typeof(string));
    
            var pemid_RangoFinalParameter = pemid_RangoFinal != null ?
                new ObjectParameter("pemid_RangoFinal", pemid_RangoFinal) :
                new ObjectParameter("pemid_RangoFinal", typeof(string));
    
            var pemid_FechaLimiteParameter = pemid_FechaLimite.HasValue ?
                new ObjectParameter("pemid_FechaLimite", pemid_FechaLimite) :
                new ObjectParameter("pemid_FechaLimite", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_Vent_tbPuntoEmisionDetalle_Insert_Result>("UDP_Vent_tbPuntoEmisionDetalle_Insert", pemi_IdParameter, dfisc_IdParameter, pemid_RangoInicioParameter, pemid_RangoFinalParameter, pemid_FechaLimiteParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> UDP_Vent_tbCliente_Insert(Nullable<byte> tpi_Id, string clte_Identificacion, Nullable<bool> clte_EsPersonaNatural, string clte_Nombres, string clte_Apellidos, Nullable<System.DateTime> clte_FechaNacimiento, string clte_Nacionalidad, string clte_Sexo, string clte_Telefono, string clte_NombreComercial, string clte_RazonSocial, string clte_ContactoNombre, string clte_ContactoEmail, string clte_ContactoTelefono, Nullable<System.DateTime> clte_FechaConstitucion, string mun_Codigo, string clte_Direccion, string clte_CorreoElectronico, Nullable<bool> clte_EsActivo, string clte_RazonInactivo, Nullable<bool> clte_ConCredito, Nullable<bool> clte_EsMinorista, string clte_Observaciones)
        {
            var tpi_IdParameter = tpi_Id.HasValue ?
                new ObjectParameter("tpi_Id", tpi_Id) :
                new ObjectParameter("tpi_Id", typeof(byte));
    
            var clte_IdentificacionParameter = clte_Identificacion != null ?
                new ObjectParameter("clte_Identificacion", clte_Identificacion) :
                new ObjectParameter("clte_Identificacion", typeof(string));
    
            var clte_EsPersonaNaturalParameter = clte_EsPersonaNatural.HasValue ?
                new ObjectParameter("clte_EsPersonaNatural", clte_EsPersonaNatural) :
                new ObjectParameter("clte_EsPersonaNatural", typeof(bool));
    
            var clte_NombresParameter = clte_Nombres != null ?
                new ObjectParameter("clte_Nombres", clte_Nombres) :
                new ObjectParameter("clte_Nombres", typeof(string));
    
            var clte_ApellidosParameter = clte_Apellidos != null ?
                new ObjectParameter("clte_Apellidos", clte_Apellidos) :
                new ObjectParameter("clte_Apellidos", typeof(string));
    
            var clte_FechaNacimientoParameter = clte_FechaNacimiento.HasValue ?
                new ObjectParameter("clte_FechaNacimiento", clte_FechaNacimiento) :
                new ObjectParameter("clte_FechaNacimiento", typeof(System.DateTime));
    
            var clte_NacionalidadParameter = clte_Nacionalidad != null ?
                new ObjectParameter("clte_Nacionalidad", clte_Nacionalidad) :
                new ObjectParameter("clte_Nacionalidad", typeof(string));
    
            var clte_SexoParameter = clte_Sexo != null ?
                new ObjectParameter("clte_Sexo", clte_Sexo) :
                new ObjectParameter("clte_Sexo", typeof(string));
    
            var clte_TelefonoParameter = clte_Telefono != null ?
                new ObjectParameter("clte_Telefono", clte_Telefono) :
                new ObjectParameter("clte_Telefono", typeof(string));
    
            var clte_NombreComercialParameter = clte_NombreComercial != null ?
                new ObjectParameter("clte_NombreComercial", clte_NombreComercial) :
                new ObjectParameter("clte_NombreComercial", typeof(string));
    
            var clte_RazonSocialParameter = clte_RazonSocial != null ?
                new ObjectParameter("clte_RazonSocial", clte_RazonSocial) :
                new ObjectParameter("clte_RazonSocial", typeof(string));
    
            var clte_ContactoNombreParameter = clte_ContactoNombre != null ?
                new ObjectParameter("clte_ContactoNombre", clte_ContactoNombre) :
                new ObjectParameter("clte_ContactoNombre", typeof(string));
    
            var clte_ContactoEmailParameter = clte_ContactoEmail != null ?
                new ObjectParameter("clte_ContactoEmail", clte_ContactoEmail) :
                new ObjectParameter("clte_ContactoEmail", typeof(string));
    
            var clte_ContactoTelefonoParameter = clte_ContactoTelefono != null ?
                new ObjectParameter("clte_ContactoTelefono", clte_ContactoTelefono) :
                new ObjectParameter("clte_ContactoTelefono", typeof(string));
    
            var clte_FechaConstitucionParameter = clte_FechaConstitucion.HasValue ?
                new ObjectParameter("clte_FechaConstitucion", clte_FechaConstitucion) :
                new ObjectParameter("clte_FechaConstitucion", typeof(System.DateTime));
    
            var mun_CodigoParameter = mun_Codigo != null ?
                new ObjectParameter("mun_Codigo", mun_Codigo) :
                new ObjectParameter("mun_Codigo", typeof(string));
    
            var clte_DireccionParameter = clte_Direccion != null ?
                new ObjectParameter("clte_Direccion", clte_Direccion) :
                new ObjectParameter("clte_Direccion", typeof(string));
    
            var clte_CorreoElectronicoParameter = clte_CorreoElectronico != null ?
                new ObjectParameter("clte_CorreoElectronico", clte_CorreoElectronico) :
                new ObjectParameter("clte_CorreoElectronico", typeof(string));
    
            var clte_EsActivoParameter = clte_EsActivo.HasValue ?
                new ObjectParameter("clte_EsActivo", clte_EsActivo) :
                new ObjectParameter("clte_EsActivo", typeof(bool));
    
            var clte_RazonInactivoParameter = clte_RazonInactivo != null ?
                new ObjectParameter("clte_RazonInactivo", clte_RazonInactivo) :
                new ObjectParameter("clte_RazonInactivo", typeof(string));
    
            var clte_ConCreditoParameter = clte_ConCredito.HasValue ?
                new ObjectParameter("clte_ConCredito", clte_ConCredito) :
                new ObjectParameter("clte_ConCredito", typeof(bool));
    
            var clte_EsMinoristaParameter = clte_EsMinorista.HasValue ?
                new ObjectParameter("clte_EsMinorista", clte_EsMinorista) :
                new ObjectParameter("clte_EsMinorista", typeof(bool));
    
            var clte_ObservacionesParameter = clte_Observaciones != null ?
                new ObjectParameter("clte_Observaciones", clte_Observaciones) :
                new ObjectParameter("clte_Observaciones", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UDP_Vent_tbCliente_Insert", tpi_IdParameter, clte_IdentificacionParameter, clte_EsPersonaNaturalParameter, clte_NombresParameter, clte_ApellidosParameter, clte_FechaNacimientoParameter, clte_NacionalidadParameter, clte_SexoParameter, clte_TelefonoParameter, clte_NombreComercialParameter, clte_RazonSocialParameter, clte_ContactoNombreParameter, clte_ContactoEmailParameter, clte_ContactoTelefonoParameter, clte_FechaConstitucionParameter, mun_CodigoParameter, clte_DireccionParameter, clte_CorreoElectronicoParameter, clte_EsActivoParameter, clte_RazonInactivoParameter, clte_ConCreditoParameter, clte_EsMinoristaParameter, clte_ObservacionesParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> UDP_Vent_tbCliente_Update(Nullable<int> clte_Id, string clte_Identificacion, Nullable<bool> clte_EsPersonaNatural, string clte_Nombres, string clte_Apellidos, Nullable<System.DateTime> clte_FechaNacimiento, string clte_Nacionalidad, string clte_Sexo, string clte_Telefono, string clte_NombreComercial, string clte_RazonSocial, string clte_ContactoNombre, string clte_ContactoEmail, string clte_ContactoTelefono, Nullable<System.DateTime> clte_FechaConstitucion, string mun_Codigo, string clte_Direccion, string clte_CorreoElectronico, Nullable<bool> clte_EsActivo, string clte_RazonInactivo, Nullable<bool> clte_ConCredito, Nullable<bool> clte_EsMinorista, string clte_Observaciones, Nullable<int> clte_UsuarioCrea, Nullable<System.DateTime> clte_FechaCrea)
        {
            var clte_IdParameter = clte_Id.HasValue ?
                new ObjectParameter("clte_Id", clte_Id) :
                new ObjectParameter("clte_Id", typeof(int));
    
            var clte_IdentificacionParameter = clte_Identificacion != null ?
                new ObjectParameter("clte_Identificacion", clte_Identificacion) :
                new ObjectParameter("clte_Identificacion", typeof(string));
    
            var clte_EsPersonaNaturalParameter = clte_EsPersonaNatural.HasValue ?
                new ObjectParameter("clte_EsPersonaNatural", clte_EsPersonaNatural) :
                new ObjectParameter("clte_EsPersonaNatural", typeof(bool));
    
            var clte_NombresParameter = clte_Nombres != null ?
                new ObjectParameter("clte_Nombres", clte_Nombres) :
                new ObjectParameter("clte_Nombres", typeof(string));
    
            var clte_ApellidosParameter = clte_Apellidos != null ?
                new ObjectParameter("clte_Apellidos", clte_Apellidos) :
                new ObjectParameter("clte_Apellidos", typeof(string));
    
            var clte_FechaNacimientoParameter = clte_FechaNacimiento.HasValue ?
                new ObjectParameter("clte_FechaNacimiento", clte_FechaNacimiento) :
                new ObjectParameter("clte_FechaNacimiento", typeof(System.DateTime));
    
            var clte_NacionalidadParameter = clte_Nacionalidad != null ?
                new ObjectParameter("clte_Nacionalidad", clte_Nacionalidad) :
                new ObjectParameter("clte_Nacionalidad", typeof(string));
    
            var clte_SexoParameter = clte_Sexo != null ?
                new ObjectParameter("clte_Sexo", clte_Sexo) :
                new ObjectParameter("clte_Sexo", typeof(string));
    
            var clte_TelefonoParameter = clte_Telefono != null ?
                new ObjectParameter("clte_Telefono", clte_Telefono) :
                new ObjectParameter("clte_Telefono", typeof(string));
    
            var clte_NombreComercialParameter = clte_NombreComercial != null ?
                new ObjectParameter("clte_NombreComercial", clte_NombreComercial) :
                new ObjectParameter("clte_NombreComercial", typeof(string));
    
            var clte_RazonSocialParameter = clte_RazonSocial != null ?
                new ObjectParameter("clte_RazonSocial", clte_RazonSocial) :
                new ObjectParameter("clte_RazonSocial", typeof(string));
    
            var clte_ContactoNombreParameter = clte_ContactoNombre != null ?
                new ObjectParameter("clte_ContactoNombre", clte_ContactoNombre) :
                new ObjectParameter("clte_ContactoNombre", typeof(string));
    
            var clte_ContactoEmailParameter = clte_ContactoEmail != null ?
                new ObjectParameter("clte_ContactoEmail", clte_ContactoEmail) :
                new ObjectParameter("clte_ContactoEmail", typeof(string));
    
            var clte_ContactoTelefonoParameter = clte_ContactoTelefono != null ?
                new ObjectParameter("clte_ContactoTelefono", clte_ContactoTelefono) :
                new ObjectParameter("clte_ContactoTelefono", typeof(string));
    
            var clte_FechaConstitucionParameter = clte_FechaConstitucion.HasValue ?
                new ObjectParameter("clte_FechaConstitucion", clte_FechaConstitucion) :
                new ObjectParameter("clte_FechaConstitucion", typeof(System.DateTime));
    
            var mun_CodigoParameter = mun_Codigo != null ?
                new ObjectParameter("mun_Codigo", mun_Codigo) :
                new ObjectParameter("mun_Codigo", typeof(string));
    
            var clte_DireccionParameter = clte_Direccion != null ?
                new ObjectParameter("clte_Direccion", clte_Direccion) :
                new ObjectParameter("clte_Direccion", typeof(string));
    
            var clte_CorreoElectronicoParameter = clte_CorreoElectronico != null ?
                new ObjectParameter("clte_CorreoElectronico", clte_CorreoElectronico) :
                new ObjectParameter("clte_CorreoElectronico", typeof(string));
    
            var clte_EsActivoParameter = clte_EsActivo.HasValue ?
                new ObjectParameter("clte_EsActivo", clte_EsActivo) :
                new ObjectParameter("clte_EsActivo", typeof(bool));
    
            var clte_RazonInactivoParameter = clte_RazonInactivo != null ?
                new ObjectParameter("clte_RazonInactivo", clte_RazonInactivo) :
                new ObjectParameter("clte_RazonInactivo", typeof(string));
    
            var clte_ConCreditoParameter = clte_ConCredito.HasValue ?
                new ObjectParameter("clte_ConCredito", clte_ConCredito) :
                new ObjectParameter("clte_ConCredito", typeof(bool));
    
            var clte_EsMinoristaParameter = clte_EsMinorista.HasValue ?
                new ObjectParameter("clte_EsMinorista", clte_EsMinorista) :
                new ObjectParameter("clte_EsMinorista", typeof(bool));
    
            var clte_ObservacionesParameter = clte_Observaciones != null ?
                new ObjectParameter("clte_Observaciones", clte_Observaciones) :
                new ObjectParameter("clte_Observaciones", typeof(string));
    
            var clte_UsuarioCreaParameter = clte_UsuarioCrea.HasValue ?
                new ObjectParameter("clte_UsuarioCrea", clte_UsuarioCrea) :
                new ObjectParameter("clte_UsuarioCrea", typeof(int));
    
            var clte_FechaCreaParameter = clte_FechaCrea.HasValue ?
                new ObjectParameter("clte_FechaCrea", clte_FechaCrea) :
                new ObjectParameter("clte_FechaCrea", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UDP_Vent_tbCliente_Update", clte_IdParameter, clte_IdentificacionParameter, clte_EsPersonaNaturalParameter, clte_NombresParameter, clte_ApellidosParameter, clte_FechaNacimientoParameter, clte_NacionalidadParameter, clte_SexoParameter, clte_TelefonoParameter, clte_NombreComercialParameter, clte_RazonSocialParameter, clte_ContactoNombreParameter, clte_ContactoEmailParameter, clte_ContactoTelefonoParameter, clte_FechaConstitucionParameter, mun_CodigoParameter, clte_DireccionParameter, clte_CorreoElectronicoParameter, clte_EsActivoParameter, clte_RazonInactivoParameter, clte_ConCreditoParameter, clte_EsMinoristaParameter, clte_ObservacionesParameter, clte_UsuarioCreaParameter, clte_FechaCreaParameter);
        }
    }
}
