//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    
    public partial class SDP_Inv_tbBodegaDetalle_Select_Producto_Result1
    {
        public string prod_Codigo { get; set; }
        public string prod_Marca { get; set; }
        public string prod_Modelo { get; set; }
        public string prod_Descripcion { get; set; }
        public string pcat_Nombre { get; set; }
        public string pscat_Descripcion { get; set; }
        public string uni_Descripcion { get; set; }
        public string prod_CodigoBarras { get; set; }
    }
}
