//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    
    public partial class SPGetResponsableBodega_Result2
    {
        public int bod_Id { get; set; }
        public short bod_ResponsableBodega { get; set; }
        public string emp_Nombres { get; set; }
    }
}
