//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_ZORZAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbActividadEconomica
    {
        public int acte_Id { get; set; }
        public string acte_Descripcion { get; set; }
        public string acte_UsuarioCrea { get; set; }
        public System.DateTime acte_FechaCrea { get; set; }
        public string acte_UsuarioModifica { get; set; }
        public System.DateTime acte_FechaModifica { get; set; }
    }
}
