//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbActividadEconomica
    {
        public short acte_Id { get; set; }
        public string acte_Descripcion { get; set; }
        public int acte_UsuarioCrea { get; set; }
        public System.DateTime acte_FechaCrea { get; set; }
        public Nullable<int> acte_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> acte_FechaModifica { get; set; }
    
        public virtual tbUsuario tbUsuario { get; set; }
        public virtual tbUsuario tbUsuario1 { get; set; }
    }
}
