//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_ZORZAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbArqueoCaja
    {
        public int aqcja_Id { get; set; }
        public short cja_Id { get; set; }
        public System.DateTime aqcja_Fecha { get; set; }
        public System.DateTime aqcja_FechaInicio { get; set; }
        public System.DateTime aqcja_FechaFin { get; set; }
        public decimal aqcja_SaldoInicial { get; set; }
        public decimal aqcja_SaldoFinal { get; set; }
        public decimal aqcja_MontoEfectivo { get; set; }
        public decimal aqcja_MontoCheque { get; set; }
        public decimal aqcja_MontoTCoTD { get; set; }
        public decimal aqcja_MontoNotaCredito { get; set; }
        public decimal aqcja_MontoCupon { get; set; }
        public int aqcja_UsuarioCrea { get; set; }
        public System.DateTime aqcja_FechaCrea { get; set; }
        public Nullable<int> aqcja_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> aqcja_FechaModifico { get; set; }
    
        public virtual tbCaja1 tbCaja1 { get; set; }
    }
}
