//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5_SeedProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbArqueoCaja
    {
        public int aqcja_Codigo { get; set; }
        public string sucur_Codigo { get; set; }
        public string cja_Codigo { get; set; }
        public System.DateTime aqcja_Fecha { get; set; }
        public System.DateTime aqcja_HoraInicio { get; set; }
        public System.DateTime aqcja_HoraFinal { get; set; }
        public decimal aqcja_SaldoInicial { get; set; }
        public decimal aqcja_SaldoFinal { get; set; }
        public decimal aqcja_MontoEfectivo { get; set; }
        public decimal aqcja_MontoCheque { get; set; }
        public decimal aqcja_Total { get; set; }
        public decimal aqcja_Diferencia { get; set; }
        public string aqcja_UsuarioCrea { get; set; }
        public Nullable<System.DateTime> aqcja_FechaCrea { get; set; }
        public string aqcja_UsuarioModifica { get; set; }
        public System.DateTime aqcja_FechaModifico { get; set; }
    
        public virtual tbSucursal tbSucursal { get; set; }
        public virtual tbCaja1 tbCaja1 { get; set; }
    }
}
