//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5_SeedProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAvales
    {
        public string aval_Codigo { get; set; }
        public string aval_Nombre { get; set; }
        public string aval_Apellido { get; set; }
        public string aval_Telefono { get; set; }
        public string aval_Direccion { get; set; }
        public string aval_Parentesco { get; set; }
        public string aval_LugardeTrabajo { get; set; }
        public string aval_Cargo { get; set; }
        public string aval_DireccionTrabajo { get; set; }
    }
}
