//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5_SeedProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBanco
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbBanco()
        {
            this.tbCuentasBanco = new HashSet<tbCuentasBanco>();
        }
    
        public int ban_Id { get; set; }
        public string ban_Nombre { get; set; }
        public string ban_NombreContacto { get; set; }
        public string ban_TelefonoContacto { get; set; }
        public string ban_UsuarioCrea { get; set; }
        public System.DateTime ban_FechaCrea { get; set; }
        public string ban_UsuarioModifica { get; set; }
        public System.DateTime ban_FechaModifica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCuentasBanco> tbCuentasBanco { get; set; }
    }
}
