//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5_SeedProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBodega
    {
        public int Bdga_Codigo { get; set; }
        public string Bdga_Encargado { get; set; }
        public string Bdga_Contacto { get; set; }
        public string estad_Codigo { get; set; }
        public string dpto_Codigo { get; set; }
        public string mpio_Codigo { get; set; }
        public string Bdga_Capacidad { get; set; }
        public string Bdga_Zona { get; set; }
        public int tpbdga_Codigo { get; set; }
    }
}
