//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5_SeedProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCaja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbCaja()
        {
            this.tbArqueoCaja = new HashSet<tbArqueoCaja>();
            this.tbFactura = new HashSet<tbFactura>();
            this.tbSolicitudEfectivo = new HashSet<tbSolicitudEfectivo>();
        }
    
        public string cja_Codigo { get; set; }
        public string cja_Descripcion { get; set; }
        public string sucur_Codigo { get; set; }
        public string cja_UsuarioCrea { get; set; }
        public Nullable<System.DateTime> cja_FechaCrea { get; set; }
        public string cja_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> cja_FechaModifica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbArqueoCaja> tbArqueoCaja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbFactura> tbFactura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSolicitudEfectivo> tbSolicitudEfectivo { get; set; }
        public virtual tbSucursal tbSucursal { get; set; }
    }
}
