//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_ZORZAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDevolucionDetalle
    {
        public string ddv_Codigo { get; set; }
        public string dev_Codigo { get; set; }
        public string prod_Codigo { get; set; }
        public int ddv_CantidadProducto { get; set; }
        public string ddv_Descripcion { get; set; }
        public string ddv_UsuarioCrea { get; set; }
        public Nullable<System.DateTime> ddv_FechaCrea { get; set; }
        public string ddv_UsuarioModifa { get; set; }
        public Nullable<System.DateTime> ddv_FechaModifa { get; set; }
    
        public virtual tbProducto tbProducto { get; set; }
    }
}
