//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5_SeedProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDetallePedidos
    {
        public string dped_CodDetallePedido { get; set; }
        public int dped_Cantidad { get; set; }
        public string dep_CodPedido { get; set; }
        public int prod_Codigo { get; set; }
    }
}
