//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDocumentoFiscal
    {
        public byte dfisc_Id { get; set; }
        public string dfisc_Descripcion { get; set; }
        public int dfisc_UsuarioCrea { get; set; }
        public System.DateTime dfisc_FechaCrea { get; set; }
        public Nullable<int> dfisc_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> dfisc_FechaModifica { get; set; }
    
        public virtual tbUsuario tbUsuario { get; set; }
        public virtual tbUsuario tbUsuario1 { get; set; }
    }
}
