//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5_SeedProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEmpaqueCaja
    {
        public int EmpCaja_IDEmpaqueCaja { get; set; }
        public string EmpCaja_BodegaDespacho { get; set; }
        public string EmpCaja_BodegaRecibe { get; set; }
        public string EmpCaja_NombreProducto { get; set; }
        public int EmpCaja_Cantidad { get; set; }
        public string EmpCaja_Observaciones { get; set; }
    }
}
