//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_ZORZAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEmpleados
    {
        public short emp_Id { get; set; }
        public string emp_Nombres { get; set; }
        public string emp_Apellidos { get; set; }
        public string emp_Sexo { get; set; }
        public System.DateTime emp_FechaNacimiento { get; set; }
        public byte tpi_Id { get; set; }
        public string emp_Identificacion { get; set; }
        public string emp_Telefono { get; set; }
        public string emp_Correoelectronico { get; set; }
        public string emp_TipoSangre { get; set; }
        public string emp_Puesto { get; set; }
        public System.DateTime emp_FechaIngreso { get; set; }
        public string emp_Direccion { get; set; }
        public string emp_Observaciones { get; set; }
        public int emp_UsuarioCrea { get; set; }
        public System.DateTime emp_FechaCrea { get; set; }
        public Nullable<int> emp_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> emp_FechaModifica { get; set; }
    
        public virtual tbUsuario tbUsuario { get; set; }
        public virtual tbTipoIdentificacion tbTipoIdentificacion { get; set; }
    }
}
