//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5_SeedProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEntrada
    {
        public string E_IdEntrada { get; set; }
        public int E_IdInvetario { get; set; }
        public int E_IdProducto { get; set; }
        public int E_IdUnidad { get; set; }
        public decimal E_PrecioUnitario { get; set; }
        public System.DateTime E_FechaEntrada { get; set; }
        public int E_IdBodega { get; set; }
        public int E_IdUsuario { get; set; }
    }
}
