//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_ZORZAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEntrada
    {
        public int ent_Id { get; set; }
        public string ent_NumeroFormato { get; set; }
        public System.DateTime ent_Fecha { get; set; }
        public int bod_Id { get; set; }
        public byte estm_Id { get; set; }
        public int prov_Id { get; set; }
        public decimal ent_CompraNumero { get; set; }
        public System.DateTime ent_CompraFecha { get; set; }
        public string fact_Codigo { get; set; }
        public string ent_RazonDevolucion { get; set; }
        public string ent_BodegaDestino { get; set; }
        public byte tent_Id { get; set; }
        public int ent_UsuarioCrea { get; set; }
        public Nullable<System.DateTime> ent_FechaCrea { get; set; }
        public Nullable<int> ent_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> ent_FechaModifica { get; set; }
    
        public virtual tbTiposEntrada tbTiposEntrada { get; set; }
        public virtual tbBodega tbBodega { get; set; }
        public virtual tbEstadoMovimiento tbEstadoMovimiento { get; set; }
        public virtual tbFactura tbFactura { get; set; }
        public virtual tbProveedor tbProveedor { get; set; }
    }
}
