//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_ZORZAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEstadoFactura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbEstadoFactura()
        {
            this.tbFactura = new HashSet<tbFactura>();
            this.tbFacturaHistorica = new HashSet<tbFacturaHistorica>();
        }
    
        public byte esfac_Id { get; set; }
        public string esfac_Descripcion { get; set; }
        public int esfac_UsuarioCrea { get; set; }
        public System.DateTime esfac_FechaCrea { get; set; }
        public Nullable<int> esfac_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> esfac_FechaModifica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbFactura> tbFactura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbFacturaHistorica> tbFacturaHistorica { get; set; }
    }
}
