//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5_SeedProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEstadoFactura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbEstadoFactura()
        {
            this.tbFactura = new HashSet<tbFactura>();
        }
    
        public byte esfac_Id { get; set; }
        public string esfac_Descripcion { get; set; }
        public string esfac_UsuarioCrea { get; set; }
        public string esfac_UsuarioModifico { get; set; }
        public System.DateTime esfac_FechaAgrego { get; set; }
        public Nullable<System.DateTime> esfac_FechaModifico { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbFactura> tbFactura { get; set; }
    }
}
