//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_ZORZAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEstadoPedido
    {
        public byte esped_Id { get; set; }
        public string esped_Descripcion { get; set; }
        public int esped_UsuarioCrea { get; set; }
        public System.DateTime esped_FechaCrea { get; set; }
        public Nullable<int> esped_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> esped_FechaModifica { get; set; }
    }
}
