//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5_SeedProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbExoneraciones
    {
        public int ex_Codigo { get; set; }
        public string clte_RTN { get; set; }
        public System.DateTime ex_FechaEmision { get; set; }
        public System.DateTime ex_FechaInicial { get; set; }
        public System.DateTime ex_FechaFinal { get; set; }
        public string ex_Imagen { get; set; }
    }
}
