//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5_SeedProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbFacturas
    {
        public string fact_Codigo { get; set; }
        public string clte_Rtn { get; set; }
        public int tpago_Codigo { get; set; }
        public int fpago_Codigo { get; set; }
        public string scs_Codigo { get; set; }
        public string Usuario_Nombre { get; set; }
        public int tcam_Codigo { get; set; }
        public System.DateTime fact_Fecha { get; set; }
    
        public virtual tbDetallesFactura tbDetallesFactura { get; set; }
    }
}
