//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbIdentificacionCliente
    {
        public byte tpi_Id { get; set; }
        public bool clte_ConsumidorFinal { get; set; }
    
        public virtual tbTipoIdentificacion tbTipoIdentificacion { get; set; }
    }
}
