//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMovimientoCaja
    {
        public int mocja_Id { get; set; }
        public short cja_Id { get; set; }
        public Nullable<System.DateTime> mocja_FechaApertura { get; set; }
        public int mocja_UsuarioApertura { get; set; }
        public Nullable<System.DateTime> mocja_FechaArqueo { get; set; }
        public int mocja_UsuarioArquea { get; set; }
        public Nullable<System.DateTime> mocja_FechaAceptacion { get; set; }
        public int mocja_UsuarioAceptacion { get; set; }
        public int mocja_UsuarioCrea { get; set; }
        public System.DateTime mocja_FechaCrea { get; set; }
        public Nullable<int> mocja_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> mocja_FechaModifica { get; set; }
    
        public virtual tbUsuario tbUsuario { get; set; }
        public virtual tbUsuario tbUsuario1 { get; set; }
        public virtual tbUsuario tbUsuario2 { get; set; }
        public virtual tbUsuario tbUsuario3 { get; set; }
        public virtual tbUsuario tbUsuario4 { get; set; }
        public virtual tbCaja tbCaja { get; set; }
    }
}
