//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5_SeedProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPagos
    {
        public int pgCodPago { get; set; }
        public string fact_Codigo { get; set; }
        public System.DateTime pgFechaPago { get; set; }
        public decimal pgMonto { get; set; }
        public int tcam_Codigo { get; set; }
        public int tpago_Codigo { get; set; }
    }
}
