//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbParametro
    {
        public byte par_Id { get; set; }
        public string par_NombreEmpresa { get; set; }
        public string par_TelefonoEmpresa { get; set; }
        public string par_CorreoEmpresa { get; set; }
        public string par_PathLogo { get; set; }
        public short mnda_Id { get; set; }
        public int par_RolGerenteTienda { get; set; }
        public int par_RolCreditoCobranza { get; set; }
        public int par_RolSupervisorCaja { get; set; }
        public int par_RolCajero { get; set; }
        public int par_RolAuditor { get; set; }
        public short par_SucursalPrincipal { get; set; }
        public int par_UsuarioCrea { get; set; }
        public System.DateTime par_FechaCrea { get; set; }
        public Nullable<int> par_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> par_FechaModifica { get; set; }
    
        public virtual tbUsuario tbUsuario { get; set; }
        public virtual tbMoneda tbMoneda { get; set; }
        public virtual tbUsuario tbUsuario1 { get; set; }
    }
}
