//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_ZORZAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbPago()
        {
            this.tbFactura1 = new HashSet<tbFactura>();
        }
    
        public int pago_Id { get; set; }
        public string fact_Codigo { get; set; }
        public int tpa_Id { get; set; }
        public decimal pago_Totalpagos { get; set; }
        public decimal pago_Totalcambio { get; set; }
        public string pago_Emisor { get; set; }
        public string pago_Cuenta { get; set; }
        public Nullable<System.DateTime> pago_FechaVencimiento { get; set; }
        public string pago_Titular_ { get; set; }
        public string pago_UsuarioCrea { get; set; }
        public System.DateTime pago_FechaCrea { get; set; }
        public string pago_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> pago_FechaModifica { get; set; }
    
        public virtual tbFactura tbFactura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbFactura> tbFactura1 { get; set; }
        public virtual tbTipoPago tbTipoPago { get; set; }
    }
}
