//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5_SeedProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPersonasJuridicas
    {
        public string clte_RTN { get; set; }
        public string clte_RazonSocial { get; set; }
        public string clte_RazonComercial { get; set; }
        public string clte_Telefono { get; set; }
        public string clte_Email { get; set; }
    
        public virtual tbClientes tbClientes { get; set; }
    }
}
