//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5_SeedProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPedido
    {
        public int ped_Codigo { get; set; }
        public Nullable<System.DateTime> ped_Fecha { get; set; }
        public Nullable<System.DateTime> ped_FechaEntrega { get; set; }
        public Nullable<int> clte_id { get; set; }
        public string sucur_Codigo { get; set; }
        public string ped_UsuarioCrea { get; set; }
        public Nullable<System.DateTime> ped__FechaCrea { get; set; }
        public string ped__UsuarioModifica { get; set; }
        public Nullable<System.DateTime> ped_FechaModica { get; set; }
    
        public virtual tbCliente tbCliente { get; set; }
        public virtual tbSucursal tbSucursal { get; set; }
    }
}
