//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_ZORZAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPedido
    {
        public int ped_Id { get; set; }
        public System.DateTime ped_FechaElaboracion { get; set; }
        public System.DateTime ped_FechaEntrega { get; set; }
        public int clte_Id { get; set; }
        public short suc_Id { get; set; }
        public long fact_Id { get; set; }
        public int ped_UsuarioCrea { get; set; }
        public System.DateTime ped_FechaCrea { get; set; }
        public Nullable<int> ped_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> ped_FechaModica { get; set; }
    
        public virtual tbUsuario tbUsuario { get; set; }
        public virtual tbUsuario tbUsuario1 { get; set; }
        public virtual tbCliente tbCliente { get; set; }
        public virtual tbFactura tbFactura { get; set; }
        public virtual tbSucursal tbSucursal { get; set; }
    }
}
