//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5_SeedProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPedidos
    {
        public string ped_CodPedido { get; set; }
        public string su_CodSucursal { get; set; }
        public System.DateTime ped_FechaPedido { get; set; }
        public System.DateTime ped_FechaEntrega { get; set; }
        public string ctle_RTN { get; set; }
    }
}
