//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_ZORZAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProductoSubcategoria
    {
        public int pscat_Id { get; set; }
        public string pscat_Descripcion { get; set; }
        public int pcat_Id { get; set; }
        public byte pscat_EsActiva { get; set; }
        public int pscat_UsuarioCrea { get; set; }
        public System.DateTime pscat_FechaCrea { get; set; }
        public Nullable<int> pscat_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> pscat_FechaModifica { get; set; }
    
        public virtual tbUsuario tbUsuario { get; set; }
        public virtual tbEstadoMovimiento tbEstadoMovimiento { get; set; }
        public virtual tbProductoCategoria tbProductoCategoria { get; set; }
    }
}
