//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5_SeedProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPuntoEmision
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbPuntoEmision()
        {
            this.tbPuntoEmisionDetalle = new HashSet<tbPuntoEmisionDetalle>();
        }
    
        public string pe_Codigo { get; set; }
        public string sucur_Codigo { get; set; }
        public string pe_NumeroCAI { get; set; }
        public string pe_UsuarioCrea { get; set; }
        public Nullable<System.DateTime> pe_FechaCrea { get; set; }
        public string pe_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> pe_FechaModifica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPuntoEmisionDetalle> tbPuntoEmisionDetalle { get; set; }
        public virtual tbSucursal tbSucursal { get; set; }
    }
}
