//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_ZORZAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSalida
    {
        public int sal_Id { get; set; }
        public int bod_Id { get; set; }
        public long fact_Id { get; set; }
        public System.DateTime sal_FechaSalida { get; set; }
        public byte estm_Id { get; set; }
        public string box_Id { get; set; }
        public byte tsal_Id { get; set; }
        public string sal_RazonDevolucion { get; set; }
        public int sal_UsuarioCrea { get; set; }
        public System.DateTime sal_FechaCrea { get; set; }
        public Nullable<int> sal_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> sal_FechaModifica { get; set; }
    
        public virtual tbBodega tbBodega { get; set; }
        public virtual tbFactura tbFactura { get; set; }
    }
}
