//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5_SeedProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSalidaDetalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbSalidaDetalle()
        {
            this.tbCaja = new HashSet<tbCaja>();
        }
    
        public int sald_Id { get; set; }
        public string prod_Codigo { get; set; }
        public int bod_Id { get; set; }
        public string bod_ResponsableBodega { get; set; }
        public int sald_UsuarioCrea { get; set; }
        public System.DateTime sald_FechaCrea { get; set; }
        public int sald_UsuarioModifica { get; set; }
        public System.DateTime sald_FechaModifica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCaja> tbCaja { get; set; }
        public virtual tbProducto tbProducto { get; set; }
    }
}
