//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5_SeedProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSolicitudCredito
    {
        public int cred_Id { get; set; }
        public int clte_Id { get; set; }
        public byte escre_Id { get; set; }
        public System.DateTime cred_FechaSolicitud { get; set; }
        public System.DateTime cred_FechaAprobacion { get; set; }
        public decimal cred_MontoSolicitud { get; set; }
        public decimal cred_MontoAprobacion { get; set; }
        public int cred_DiasSolicitud { get; set; }
        public int cred_DiasAprobacion { get; set; }
        public string cred_UsuarioCrea { get; set; }
        public System.DateTime cred_FechaCrea { get; set; }
        public string cred_UsuarioModicacion { get; set; }
        public System.DateTime cred_FechaModifica { get; set; }
    
        public virtual tbCliente tbCliente { get; set; }
        public virtual tbEstadoSolicitudCredito tbEstadoSolicitudCredito { get; set; }
    }
}
