//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSolicitudEfectivoDetalle
    {
        public int solefd_Id { get; set; }
        public int solef_Id { get; set; }
        public short solefd_Cantidad { get; set; }
        public short tdmi_Id { get; set; }
        public Nullable<int> solefd_UsuarioCrea { get; set; }
        public Nullable<System.DateTime> solefd_FechaCrea { get; set; }
        public Nullable<int> solefd_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> solefd_FechaModifica { get; set; }
    
        public virtual tbUsuario tbUsuario { get; set; }
        public virtual tbUsuario tbUsuario1 { get; set; }
        public virtual tbSolicitudEfectivo tbSolicitudEfectivo { get; set; }
    }
}
