//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSolicitudEfectivoDetalle
    {
        public int soled_Id { get; set; }
        public int solef_Id { get; set; }
        public short deno_Id { get; set; }
        public short soled_CantidadSolicitada { get; set; }
        public short soled_CantidadEntregada { get; set; }
        public decimal soled_MontoEntregado { get; set; }
        public int soled_UsuarioCrea { get; set; }
        public System.DateTime soled_FechaCrea { get; set; }
        public Nullable<int> soled_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> soled_FechaModifica { get; set; }
    
        public virtual tbUsuario tbUsuario { get; set; }
        public virtual tbUsuario tbUsuario1 { get; set; }
        public virtual tbDenominacion tbDenominacion { get; set; }
        public virtual tbSolicitudEfectivo tbSolicitudEfectivo { get; set; }
    }
}
