//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5_SeedProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSucursal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbSucursal()
        {
            this.tbArqueoCaja = new HashSet<tbArqueoCaja>();
            this.tbCaja1 = new HashSet<tbCaja1>();
            this.tbCuponDescuento = new HashSet<tbCuponDescuento>();
            this.tbFactura = new HashSet<tbFactura>();
            this.tbPedido = new HashSet<tbPedido>();
            this.tbPuntoEmision = new HashSet<tbPuntoEmision>();
        }
    
        public string sucur_Codigo { get; set; }
        public string mun_Id { get; set; }
        public string sucur_Correo { get; set; }
        public string sucur_Direccion { get; set; }
        public string sucur_Telefono { get; set; }
        public string sucur_UsuarioCrea { get; set; }
        public Nullable<System.DateTime> sucur_FechaCrea { get; set; }
        public string sucur_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> sucur_FechaModifica { get; set; }
    
        public virtual tbMunicipio tbMunicipio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbArqueoCaja> tbArqueoCaja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCaja1> tbCaja1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCuponDescuento> tbCuponDescuento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbFactura> tbFactura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPedido> tbPedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPuntoEmision> tbPuntoEmision { get; set; }
    }
}
