//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTipoDenominacion
    {
        public short tdmi_Id { get; set; }
        public string tdmi_BilleteMoneda { get; set; }
        public int tdmi_UsuarioCrea { get; set; }
        public System.DateTime tdmi_FechaCrea { get; set; }
        public Nullable<int> tdmi_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> tdmi_FechaModifica { get; set; }
    
        public virtual tbUsuario tbUsuario { get; set; }
        public virtual tbUsuario tbUsuario1 { get; set; }
    }
}
