//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    
    public partial class UDP_Vent_tbSolicitudEfectivo_Details_Result1
    {
        public int soled_Id { get; set; }
        public string deno_Descripcion { get; set; }
        public short soled_CantidadSolicitada { get; set; }
        public Nullable<decimal> MontoSolicitado { get; set; }
        public short soled_CantidadEntregada { get; set; }
        public Nullable<decimal> MontoEntregado { get; set; }
        public short deno_Id { get; set; }
    }
}
