//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    
    public partial class UDP_Vent_tbMovimientoCaja_Imprimir_Result1
    {
        public int mocja_Id { get; set; }
        public Nullable<System.DateTime> mocja_FechaApertura { get; set; }
        public int mocja_UsuarioApertura { get; set; }
        public Nullable<System.DateTime> mocja_FechaArqueo { get; set; }
        public int mocja_UsuarioArquea { get; set; }
        public Nullable<System.DateTime> mocja_FechaAceptacion { get; set; }
        public int mocja_UsuarioAceptacion { get; set; }
        public string cja_Descripcion { get; set; }
        public string suc_Descripcion { get; set; }
        public short arqde_CantidadDenominacion { get; set; }
        public decimal arqde_MontoDenominacion { get; set; }
        public string deno_Descripcion { get; set; }
        public decimal deno_valor { get; set; }
        public decimal arqpg_PagosSistema { get; set; }
        public decimal arqpg_PagosConteo { get; set; }
        public string tpa_Descripcion { get; set; }
        public string Usuario_Apertura { get; set; }
        public string Usuario_Arquea { get; set; }
        public string Usuario_Aceptacion { get; set; }
    }
}
