//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    
    public partial class UDP_Vent_tbSolicitudEfectivoDetalle_Detalle_Result1
    {
        public short denoId { get; set; }
        public string DenoDescripcion { get; set; }
        public decimal valor { get; set; }
    }
}
