//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    
    public partial class UDP_Vent_tbNotaCreditoSelect_Result1
    {
        public int clte_Id { get; set; }
        public short nocre_Id { get; set; }
        public string nocre_Codigo { get; set; }
        public Nullable<decimal> nocre_Monto { get; set; }
        public bool nocre_Redimido { get; set; }
    }
}
