//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UDV_Vent_MovimientoCaja_Apertura_Detalles
    {
        public int mocja_Id { get; set; }
        public Nullable<System.DateTime> mocja_FechaApertura { get; set; }
        public int mocja_UsuarioApertura { get; set; }
        public string mnda_Abreviatura { get; set; }
        public string mnda_Nombre { get; set; }
        public short soled_CantidadEntregada { get; set; }
        public short soled_CantidadSolicitada { get; set; }
        public decimal soled_MontoEntregado { get; set; }
        public short cja_Id { get; set; }
        public string NOMBRES { get; set; }
    }
}
