//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UDV_Vent_FacturasPendientesDePago
    {
        public string clte_Identificacion { get; set; }
        public string clte_Nombres { get; set; }
        public System.DateTime fact_Fecha { get; set; }
        public string suc_Descripcion { get; set; }
        public string fact_Codigo { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<decimal> MontoFacturado { get; set; }
        public int TotalCargos { get; set; }
        public Nullable<decimal> TotalCreditos { get; set; }
        public Nullable<decimal> Saldoactual { get; set; }
    }
}
