//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UDV_Inv_Proyeccion_de_Movimiento_de_Producto
    {
        public string Prod_Codigo { get; set; }
        public string suc_Direccion { get; set; }
        public int Código_Bodega { get; set; }
        public string Nombre_de_la_Bodega { get; set; }
        public short Responsable { get; set; }
        public string Télefono { get; set; }
        public string prod_CodigoBarras { get; set; }
        public string Nombre_Producto { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Unidad_Medida { get; set; }
        public string Talla { get; set; }
        public decimal Cantidad_Inventario { get; set; }
        public decimal Promedio_Vent__Diaria { get; set; }
        public Nullable<decimal> Proyección_Días { get; set; }
        public string Creado_por_ { get; set; }
        public System.DateTime Creado_el_ { get; set; }
    }
}
