//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UDV_Vent_VentasExoneradas
    {
        public Nullable<System.DateTime> Fecha_factura { get; set; }
        public string suc_Descripcion { get; set; }
        public string prod_Codigo { get; set; }
        public string clte_Identificacion { get; set; }
        public string clte_NombreComercial { get; set; }
        public string fact_Codigo { get; set; }
        public string prod_Descripcion { get; set; }
        public Nullable<decimal> Monto_Facturado { get; set; }
        public Nullable<decimal> Impuesto_Exonerado { get; set; }
    }
}
