//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UDV_Vent_PagosPorFechas
    {
        public int Num { get; set; }
        public string RTN_Cliente { get; set; }
        public string Nombre { get; set; }
        public string Código_Factura { get; set; }
        public string tpa_Descripcion { get; set; }
        public string Cajero { get; set; }
        public decimal Saldo_Anterior { get; set; }
        public decimal Total_Pago { get; set; }
        public Nullable<System.DateTime> pago_FechaElaboracion { get; set; }
        public Nullable<decimal> Saldo_Actual { get; set; }
    }
}
