//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UDV_Vent_Factura_VentasporFecha
    {
        public int clte_Id { get; set; }
        public string clte_Identificacion { get; set; }
        public bool clte_EsPersonaNatural { get; set; }
        public string Nombres { get; set; }
        public string Tipo_cliente { get; set; }
        public string fact_Codigo { get; set; }
        public bool fact_AlCredito { get; set; }
        public string Factura_Credito { get; set; }
        public Nullable<System.DateTime> Fecha_factura { get; set; }
        public Nullable<decimal> MontoFactura { get; set; }
        public Nullable<System.DateTime> Fecha_vencimiento { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public Nullable<decimal> TotalFactura { get; set; }
    }
}
