//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UDV_Inv_PackingList
    {
        public string box_Codigo { get; set; }
        public string Descripción { get; set; }
        public string Codigo_de_Barras_ { get; set; }
        public string Producto { get; set; }
        public string Nombre { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Talla { get; set; }
        public string Unidad { get; set; }
        public decimal Cantidad { get; set; }
        public string Bodega { get; set; }
        public int Bodega_Destino { get; set; }
        public string Creado_Por_ { get; set; }
        public System.DateTime Creada_El_ { get; set; }
    }
}
