//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Vent_FacturaPago
    {
        public long fact_Id { get; set; }
        public int clte_Id { get; set; }
        public string fact_Codigo { get; set; }
        public Nullable<decimal> MontoFactura { get; set; }
        public Nullable<decimal> TotalPagado { get; set; }
        public Nullable<decimal> SaldoFactura { get; set; }
    }
}
